"""Build a clean deployment tree from an explicit allowlist; never bundle caches."""
from pathlib import Path
import shutil
import zipfile

ROOT = Path(__file__).resolve().parents[1]
TOP_LEVEL = ('app.py', 'config.py', 'requirements.txt', 'run.sh', 'README.md',
             '.gitignore', '.python-version', '.env.example')
CODE_DIRS = ('components', 'data_sources', 'models', 'storage', 'tests', 'scripts')


def deployment_files(root=ROOT):
    files = [root / name for name in TOP_LEVEL]
    files += [root / '.streamlit' / 'config.toml', root / 'data' / 'census_apportionment.csv']
    for directory in CODE_DIRS:
        files.extend(sorted((root / directory).glob('*.py')))
    for extension in ('*.md', '*.png'):
        files.extend(sorted((root / 'docs').glob(extension)))
    # Small provenance reports contain only public-source validation metadata.
    files.extend(sorted((root / 'docs').glob('*validation.json')))
    return sorted(set(files))


def package(root=ROOT):
    output = root / '.runtime' / 'deployment'
    tree = output / 'gas-weather'
    archive = output / 'gas-weather.zip'
    # This tree is generated by this script; clear only that known output.
    if tree.exists():
        shutil.rmtree(tree)
    tree.mkdir(parents=True)
    files = deployment_files(root)
    with zipfile.ZipFile(archive, 'w', compression=zipfile.ZIP_DEFLATED) as zipped:
        for source in files:
            if source.is_symlink() or not source.is_file():
                raise ValueError(f'Expected regular deployment source: {source}')
            relative = source.relative_to(root)
            destination = tree / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)
            zipped.write(source, relative.as_posix())
    return tree, archive, len(files)


if __name__ == '__main__':
    tree, archive, count = package()
    print(f'Prepared {count} files in {tree}')
    print(f'Upload archive: {archive} ({archive.stat().st_size:,} bytes)')
